# Generated by Django 5.0.2 on 2024-02-18 02:49

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("myapp", "0002_rename_name_person_person_name"),
    ]

    operations = [
        migrations.AddField(
            model_name="person",
            name="age",
            field=models.CharField(default=1, max_length=10),
            preserve_default=False,
        ),
    ]
